#pragma once
#define VIAL_KEYBOARD_UID {0xCE, 0x33, 0x62, 0x62, 0xCA, 0x0B, 0x57, 0xFC}


#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }


#define WS2812_DI_PIN GP3
#define RGBLIGHT_LED_COUNT 8

#define RGBLIGHT_EFFECT_ALTERNATING	
#define RGBLIGHT_EFFECT_BREATHING	
#define RGBLIGHT_EFFECT_CHRISTMAS	
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL	
#define RGBLIGHT_EFFECT_RGB_TEST	 
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT	
#define RGBLIGHT_EFFECT_TWINKLE

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP0
#define I2C1_SCL_PIN GP1
