VIA_ENABLE = yes
VIAL_ENABLE = yes
WS2812_DRIVER_REQUIRED = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812
WS2812_DRIVER=vendor
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

OPT_DEFS += -DHAL_USE_I2C=TRUE
